name: Android Build with Ant

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Specify the Java version you need
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: '30' # Specify the API level you need
          target: 'android-30' # Specify the target you need
          components: 'platform-tools,build-tools;30.0.3' # Specify required components

      - name: Set up Ant
        uses: cedx/setup-ant@v1
        with:
          ant-version: '1.10.12' # Specify the Ant version you need

      - name: Build with Ant
        run: ant compile release
