name: Android Build with Ant

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Specify the Java version you need
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
      - name: Set up Ant
        uses: cedx/setup-ant@v1
        with:
          optional-tasks: true
          version: '1.10.12' # Specify the Ant version you need
      - name: Install Android SDK 25
        run: |
             sdkmanager --install "platforms;android-25"
             sdkmanager --install "build-tools;25.0.3"
             yes | sdkmanager --licenses
             echo "sdk.dir=$HOME/.android/sdk"> local.properties
             android update project --target 8 --path .
      - name: Build with Ant
        run: ant compile release
